Repository fwdekker/intellij-randomness, pull requests merged in 2025-07, with the labels that each got.

#585 Implement numbering of array elements
  src/main/kotlin/com/fwdekker/randomness/array/ArrayDecorator.kt
  src/main/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditor.kt
  src/main/resources/randomness.properties
  src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditorTest.kt
  src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorTest.kt
Labels: feature

#590 Resolve HTML displayed in word list name
  src/main/kotlin/com/fwdekker/randomness/word/WordSchemeEditor.kt
  src/main/resources/randomness.properties
Labels: bug

#593 Deploy updates semi-automatically
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  build.gradle.kts
  gradle.properties
Labels: tooling

#596 Add support for special "NOW" timestamp
  src/main/kotlin/com/fwdekker/randomness/Settings.kt
  src/main/kotlin/com/fwdekker/randomness/Timestamp.kt
  src/main/kotlin/com/fwdekker/randomness/datetime/DateTimeScheme.kt
  src/main/kotlin/com/fwdekker/randomness/datetime/DateTimeSchemeEditor.kt
  src/main/kotlin/com/fwdekker/randomness/uuid/UuidScheme.kt
  src/main/kotlin/com/fwdekker/randomness/uuid/UuidSchemeEditor.kt
  src/main/resources/randomness.properties
  src/test/kotlin/com/fwdekker/randomness/TimestampTest.kt
  src/test/kotlin/com/fwdekker/randomness/uuid/UuidSchemeTest.kt
  src/test/resources/settings-upgrades/v3.3.6-v3.4.0-after.xml
Labels: feature
